coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
  
  # Tell Codecov not to ignore our utility/misc folders!
  ignore:
    - "tests/**/*" # Only ignore actual test files