name: Linting Python Code

on:
  push:
    paths:
      - '**.py'
      - '.python-version'
      - 'requirements.txt'
  pull_request:
    paths:
      - '**.py'
      - '.python-version'
      - 'requirements.txt'

jobs:
  lint:
    name: Lint Python Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: '.python-version'
        cache: 'pip' # Speeds up your workflow by caching dependencies

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Analysing the code with pylint
      run: |
        pylint --errors-only $(git ls-files '*.py')
